# Generated by Django 4.1.1 on 2022-12-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
