# Generated by Django 4.1.1 on 2022-12-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stripe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_price',
            new_name='stripe_product_id',
        ),
    ]
