# Generated by Django 4.1.1 on 2022-12-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_stripe_price_product_stripe_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_product_id',
            new_name='stripe_price',
        ),
    ]
